name       : mariadb
version    : 10.4.6
release    : 16
source     :
    - https://downloads.mariadb.com/MariaDB/mariadb-10.4.6/source/mariadb-10.4.6.tar.gz : a270fe6169a1aaf6f2cbbc945de2c954d818c48e1a0fc02fbed92ecb94678e70
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  :
    - database
    - bench : database
    - embedded : database
    - libs : programming.library
    - server : database
summary    :
    - Client for MariaDB, a community-developed fork of MySQL server
    - bench : Benchmark data for MariaDB
    - docs : MariaDB documentation
    - embedded : An embeddable MariaDB server
    - libs : MariaDB client libraries
    - server : The MariaDB server
description: |
    MariaDB server is a community developed fork of MySQL server. Started by core members of the original MySQL team, MariaDB actively works with outside developers to deliver the most featureful, stable, and sanely licensed open SQL server in the industry.
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(libarchive)
    - pkgconfig(libevent)
    - pkgconfig(liblz4)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
    - bzip2-devel
    - libaio-devel
    - lzo-devel
rundeps    :
    - perl-dbd-mysql    # For mytop command. perl-dbd-mysql in turn depends on mariadb-libs
    - perl-term-readkey # For mytop command
    - devel :
        - mariadb-libs
        - mariadb-server
    - server : mariadb
patterns   :
    - bench :
        - /usr/share/sql-bench
    - devel :
        - /usr/share/pkgconfig
    - docs :
        - /usr/share/man
        - /usr/share/doc
    - libs :
        - /usr/lib64/lib*.so*
        - /usr/lib64/mysql/plugin/dialog.so
        - /usr/lib64/mysql/plugin/mysql_clear_password.so
    - server :
        - /usr/bin/aria*
        - /usr/bin/inno*
        - /usr/bin/mariabackup
        - /usr/bin/mariadb-* # Symlinks to mysql_*
        - /usr/bin/mariadb_first_install
        - /usr/bin/mariadbd* # Symlinks to mysqld*
        - /usr/bin/myisam*
        - /usr/bin/mysql_*
        - /usr/bin/mysqld*
        - /usr/bin/mysqlhotcopy
        - /usr/bin/perror
        - /usr/bin/resolve*
        - /usr/bin/tokuft*
        - /usr/lib64/libmysqld.so*
        - /usr/lib64/mysql/plugin
        - /usr/lib64/systemd
        - /usr/lib64/sysusers.d
        - /usr/lib64/tmpfiles.d
        - /usr/sbin/mariadbd # Symlink to mysqld
        - /usr/sbin/mysqld
        - /usr/share/defaults/mysql/my.cnf.d/enable_encryption.preset
        - /usr/share/defaults/mysql/my.cnf.d/server.cnf
        - /usr/share/defaults/mysql/systemd
        - /usr/share/groonga*
        - /usr/share/mysql/*.sql
        - /usr/share/mysql/mroonga
        - /usr/share/mysql/systemd
    - embedded :
        - /usr/bin/*embedded*
    - main :
        - /usr/bin/mysql_find_rows
        - /usr/bin/mysql_plugin
        - /usr/bin/mysql_waitpid
        - /usr/bin/mysqldump
setup      : |
    %patch -p1 < $pkgfiles/0001-support-files-Add-Solus-integration.patch
    %patch -p1 < $pkgfiles/0002-storage-No-nope-and-even-more-nope.patch

    %cmake_ninja -DBUILD_CONFIG=mysql_release \
        -DENABLED_LOCAL_INFILE=ON \
        -DINSTALL_DOCDIR=share/doc/mariadb-${version} \
        -DINSTALL_DOCREADMEDIR=share/doc/mariadb-${version} \
        -DINSTALL_LIBDIR="lib%LIBSUFFIX%" \
        -DINSTALL_MANDIR=share/man \
        -DINSTALL_MYSQLSHAREDIR=share/mysql \
        -DINSTALL_MYSQLTESTDIR= \
        -DINSTALL_PLUGINDIR=lib%LIBSUFFIX%/mysql/plugin \
        -DINSTALL_SBINDIR=sbin \
        -DINSTALL_SCRIPTDIR=bin \
        -DINSTALL_SQLBENCHDIR=share \
        -DINSTALL_SUPPORTFILESDIR=share/mysql \
        -DINSTALL_SYSCONF2DIR="/usr/share/defaults/mysql/my.cnf.d" \
        -DINSTALL_SYSCONFDIR="/usr/share/defaults/mysql" \
        -DINSTALL_SYSTEMD_UNITDIR="%libdir%/systemd/system" \
        -DMYSQL_DATADIR=/var/db/mysql \
        -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
        -DPLUGIN_AUTH_GSSAPI:STRING=NO \
        -DSECURITY_HARDENED=ON \
        -DWITH_EMBEDDED_SERVER=ON \
        -DWITH_JEMALLOC=yes \
        -DWITH_LIBARCHIVE=ON \
        -DWITH_PCRE=system \
        -DWITH_READLINE=ON \
        -DWITH_SSL=system \
        -DWITH_SYSTEMD=yes \
        -DWITH_UNIT_TESTS=OFF \
        -DWITH_ZLIB=system
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/mysql.sysusers $installdir/%libdir%/sysusers.d/mysql.conf
    install -Dm00644 $pkgfiles/mysql.tmpfiles $installdir/%libdir%/tmpfiles.d/mysql.conf
    install -m00755 $pkgfiles/mariadb_first_install $installdir/usr/bin/mariadb_first_install

    # Nuke static
    rm $installdir/%libdir%/*.a

    # Dopey artifacts we don't support
    rm $installdir/usr/lib64/systemd/system/mariadb@.service
    rm $installdir/usr/sbin/rcmysql
    rm $installdir/usr/share/mysql/*.server
    rm -rf $installdir/usr/data/
    rm -rf $installdir/usr/share/defaults/mysql/init.d
    rm -rf $installdir/usr/share/defaults/mysql/logrotate.d

    # We support AppArmor, but MariaDB doesn't have a well tested policy suite yet.
    # Get back in future
    rm -rf $installdir/usr/share/mysql/policy

    # We'll handle integration ourselves.
    rm $installdir/usr/share/mysql/binary-configure

    # Add empty directory so that mariadb doesn't complain about it missing
    install -dm00755 $installdir/etc/mysql/my.cnf.d

    # Remove readmes, license files etc.
    rm -rf $installdir/usr/share/doc

    # Remove test-related binaries
    find $installdir/usr/{bin,share/man/man1} -name '*test*' -delete
