name       : mariadb
version    : 10.1.19
release    : 1
source     :
    - https://github.com/MariaDB/server/archive/mariadb-10.1.19.tar.gz : 8b545cb455c639cac62994e8864ef933c39bea8c65ff745c2a82a7395d208868
license    : GPL-2.0 LGPL-2.1
component  : database
summary    : MariaDB server is a community developed fork of MySQL server. 
description: |
    MariaDB server is a community developed fork of MySQL server. Started by core members of the original MySQL team, MariaDB actively works with outside developers to deliver the most featureful, stable, and sanely licensed open SQL server in the industry.
setup      : >
    %cmake . 
    -DCMAKE_BUILD_TYPE=Release
    -DPLUGIN_AUTH_GSSAPI:STRING=NO 
    -WITH_SYSTEMD=yes 
    -SECURITY_HARDENED=ON 
    -WITH_PCRE=system 
    -WITH_READLINE=OFF 
    -WITH_SSL=system 
    -WITH_ZLIB=system
    -DINSTALL_MANDIR=share/man
    -DINSTALL_DOCDIR=share/doc/mariadb-10.1.18
    -DINSTALL_DOCREADMEDIR=share/doc/mariadb-10.1.18
    -DINSTALL_MYSQLSHAREDIR=share/mysql
    -DINSTALL_MYSQLTESTDIR=share/mysql/test
    -DINSTALL_PLUGINDIR=lib/mysql/plugin
    -DINSTALL_SQLBENCHDIR=share/mysql/bench
    -DINSTALL_SUPPORTFILESDIR=share/mysql
    -DINSTALL_SCRIPTDIR=bin
    -DINSTALL_SBINDIR=sbin
    -DMYSQL_DATADIR=/var/db/mysql
    -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock
build      : |
    %make
install    : |
    %make_install
    %patch $workdir/support-files/mariadb.service $pkgfiles/001-fix-service-file.patch
    install -D -m 00644 $pkgfiles/mysql.sysusers $installdir/%libdir%/sysusers.d/mysql.conf
    install -D -m 00644 $workdir/support-files/mariadb.service  $installdir/%libdir%/systemd/system/mariadb.service
    mkdir -p $installdir/var/db/mysql
    chown -R 88:88 $installdir/var/db/mysql
    mkdir -p $installdir/run/mysqld
    chown -R 88:88 $installdir/run/mysqld
patterns:
    - /var/db/mysql
    - /run/mysqld
    - test:
        - /usr/share/mysql/test
