name       : mariadb
version    : 10.0.20
release    : 1
source     :
    - http://mariadb.uberglobalmirror.com//mariadb-10.0.20/source/mariadb-10.0.20.tar.gz : 3a4f6963c794977af5d5fd9ec06a337a2ad556b3a287196fddbd2243c1388b7b
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : MariaDB
description: |
    MariaDB
setup      : |
    %cmake . 
build      : |
    %make
install    : |
    %make_install
