name       : mariadb
version    : 10.1.19
release    : 2
source     :
    - https://github.com/MariaDB/server/archive/mariadb-10.1.19.tar.gz : 8b545cb455c639cac62994e8864ef933c39bea8c65ff745c2a82a7395d208868
license    :
    - GPL-2.0
    - LGPL-2.1
component  :
    - database
    - bench : database
    - embedded: database
    - server: database
    - test: database
summary    :
    - MariaDB server is a community developed fork of MySQL server.
    - bench: |
        This package provides MariaDB benchmark data
    - embedded: |
        This package provides an embeddable MariaDB server.
    - server: |
        This package provides the MariaDB server component
    - test: |
        This package provides the test components for MariaDB
    - docs: |
        This package provides MariaDB documentation
description: |
    MariaDB server is a community developed fork of MySQL server. Started by
    core members of the original MySQL team, MariaDB actively works with
    outside developers to deliver the most featureful, stable, and sanely
    licensed open SQL server in the industry.
builddeps  :
    - pkgconfig(jemalloc)
    - pkgconfig(libevent)
    - pkgconfig(libpcre)
    - libaio-devel
patterns:
    - bench:
        - /usr/share/sql-bench
    - devel:
        - /usr/share/pkgconfig
    - docs:
        - /usr/share/man
        - /usr/share/doc
    - server:
        - /usr/sbin/mysqld
        - /usr/bin/aria*
        - /usr/bin/inno*
        - /usr/bin/myisam*
        - /usr/bin/mysqld*
        - /usr/bin/mysql_*
        - /usr/bin/mysqlhotcopy
        - /usr/bin/perror
        - /usr/bin/replace
        - /usr/bin/resolve*
        - /usr/bin/tokuft*
        - /usr/lib64/systemd
        - /usr/lib64/sysusers.d
        - /usr/lib64/tmpfiles.d
        - /usr/lib64/mysql/plugin
        - /usr/lib64/libmysqld.so.*
        - /usr/share/mysql/*.sql
        - /usr/share/mysql/my-*.cnf
        - /usr/share/mysql/mroonga
        - /usr/share/mysql/systemd
    - test:
        - /usr/bin/mysqltest
        - /usr/share/mysql/test
    - embedded:
        - /usr/bin/*embedded*
    - /usr/bin/mysqldump
    - /usr/bin/mysql_find_rows
    - /usr/bin/mysql_plugin
    - /usr/bin/mysql_waitpid
rundeps    :
    - server: mariadb
setup      : |
    # TODO: Forward port the CLR stateless patches
    %cmake . \
    -DPLUGIN_AUTH_GSSAPI:STRING=NO  \
    -WITH_SYSTEMD=yes \
    -DSECURITY_HARDENED=ON \
    -DBUILD_CONFIG=mysql_release \
    -DWITH_JEMALLOC=yes \
    -DWITH_PCRE=system \
    -DWITH_READLINE=OFF \
    -DWITH_SSL=system \
    -DWITH_ZLIB=system \
    -DENABLED_LOCAL_INFILE=ON \
    -DWITH_EMBEDDED_SERVER=ON \
    -DINSTALL_LIBDIR="lib%LIBSUFFIX%" \
    -DINSTALL_MANDIR=share/man \
    -DINSTALL_DOCDIR=share/doc/mariadb-${version} \
    -DINSTALL_DOCREADMEDIR=share/doc/mariadb-${version} \
    -DINSTALL_MYSQLSHAREDIR=share/mysql \
    -DINSTALL_MYSQLTESTDIR=share/mysql/test  \
    -DINSTALL_PLUGINDIR=lib%LIBSUFFIX%/mysql/plugin \
    -DINSTALL_SQLBENCHDIR=share \
    -DINSTALL_SUPPORTFILESDIR=share/mysql \
    -DINSTALL_SYSCONF2DIR="/etc/mysql/my.cnf.d" \
    -DINSTALL_SYSCONFDIR="/etc/mysql" \
    -DINSTALL_SCRIPTDIR=bin \
    -DINSTALL_SBINDIR=sbin \
    -DMYSQL_DATADIR=/var/db/mysql \
    -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock
build      : |
    %make
install    : |
    %make_install
    %patch $workdir/support-files/mariadb.service $pkgfiles/001-fix-service-file.patch
    install -D -m 00644 $pkgfiles/mysql.sysusers $installdir/%libdir%/sysusers.d/mysql.conf
    install -D -m 00644 $pkgfiles/mysql.tmpfiles $installdir/%libdir%/tmpfiles.d/mysql.conf
    install -D -m 00644 $workdir/support-files/mariadb.service  $installdir/%libdir%/systemd/system/mariadb.service
    # Nuke static
    rm -v $installdir/%libdir%/*.a
    # Solus doesn't use selinux or apparmor currently.
    rm -rf $installdir/usr/share/mysql/policy
    # Dopey artifacts we don't support...
    rm -rfv $installdir/etc/mysql/init.d
    rm -rfv $installdir/etc/mysql/logrotate.d
    rm -rfv $installdir/usr/data/
    rm -v $installdir/usr/share/mysql/*.server
    # We'll handle integration ourselves.
    rm $installdir/usr/share/mysql/binary-configure
